### ISSUE TITLE
Add 3D cockpit model

### ISSUE THREAD

**Issue by exocetfalling** [exocetfalling/ZenithFlightSim#47]
In the shift away from exclusively drones owing to difficulties with remote display, we need a 3D cockpit. 

**Tasks**
- [ ] Add outer shell 
- [ ] Add canopy glass
- [ ] Cut holes for panels using CSG
- [ ] Add MFDs
- [ ] Add HUD
- [ ] Add standby instruments 
- [ ] Animate
